### ISSUE TITLE
WebGLよりレート計算APIを呼び出す際のCORSエラーの修正

### ISSUE THREAD

**Issue by yukinissie** [jyogi-web/ptera-api#11]
API呼び出し時のHTTPリクエストには以下を設定する必要がありそうです。

```
"Access-Control-Allow-Credentials": "true",
"Access-Control-Allow-Headers": "Accept, X-Access-Token, X-Application-Name, X-Request-Sent-Time",
"Access-Control-Allow-Methods": "GET, POST, OPTIONS",
"Access-Control-Allow-Origin": "*",
```

参考：https://docs.unity3d.com/ja/2019.4/Manual/webgl-networking.html

たしか許可するHeaderが空欄だったので最悪`*`を入れるとエラーは解消されるかもしれないです。

https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/how-to-cors.html

**Comment by Romira915** [comment]
`Access-Control-Allow-Headers`に以下を設定することでエラーは解消されました．

```
access-control-allow-origin
accept
x-access-token
x-application-name
x-request-sent-time
ptera-id
content-type
```

よって本IssueをCloseします．
